# Generated by Django 5.2 on 2025-06-17 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('year_of_production', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=50)),
                ('engine_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('power', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_doors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
